#15.773 Homework 2 (Spring 2024): Natural Langugage Processing

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow import keras

keras.utils.set_random_seed(42)

# Introduction

This homework assignment will ask you to build text classification models using BoW, GloVE and BERT as well as compare the performance of the three models.

We will work with a famous dataset in natural langauge processing called **20 Newsgroup**,  which consists of posts from an online forum under topics such as politics, religion, sports...etc. As the name suggests, there are a total of 20 topics in this dataset. The 20 Newsgroup dataset is a popular benchmark for text classification algorithms.

The entire dataset is quite large. To ensure training takes a reasonable amount of time, we will only choose 6 out of the 20 topics, including topics like religion, space (astronomy) and medicine.

In [2]:
from sklearn.datasets import fetch_20newsgroups

newsgroups_train = fetch_20newsgroups(subset='train', categories = ['alt.atheism', 'talk.religion.misc', 'comp.graphics', 'sci.space', 'sci.med', 'rec.autos'])
newsgroups_test = fetch_20newsgroups(subset='test', categories = ['alt.atheism', 'talk.religion.misc', 'comp.graphics', 'sci.space', 'sci.med', 'rec.autos'])

train_df = pd.DataFrame({'text': newsgroups_train.data, 'label': newsgroups_train.target})
test_df = pd.DataFrame({'text': newsgroups_test.data, 'label': newsgroups_test.target})

print(f"""
Train samples: {train_df.shape[0]}
Test samples: {test_df.shape[0]}
""")

train_df.head(15)

Train samples: 3222
Test samples: 2145

                                                 text  label
0   From: boylan@pi.eai.iastate.edu (Terran Boylan...      1
1   From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...      0
2   From: snichols@adobe.com (Sherri Nichols)\nSub...      3
3   From: johnm@spudge.lonestar.org (John Munsch)\...      1
4   From: Nanci Ann Miller <nm0w+@andrew.cmu.edu>\...      0
5   From: nsmca@aurora.alaska.edu\nSubject: 30826\...      4
6   From: geb@cs.pitt.edu (Gordon Banks)\nSubject:...      3
7   From: higgins@fnalf.fnal.gov (Bill Higgins-- B...      4
8   From: mmm@cup.portal.com (Mark Robert Thorson)...      3
9   From: daniel@lclark.edu (Daniel Snodgrass)\nSu...      1
10  From: geb@cs.pitt.edu (Gordon Banks)\nSubject:...      3
11  From: fulk@cs.rochester.edu (Mark Fulk)\nSubje...      3
12  From: emm@tamarack202.cray.com (Mike McConnell...      1
13  From: aas7@po.CWRU.Edu (Andrew A. Spencer)\nSu...      2
14  From: jaeger@buphy.bu.edu (Gregg Jaeger)\nSubj...      0

The distribution of labels across these 6 classes is fairly balanced.

In [3]:
train_df['label'].value_counts() / train_df.shape[0]

label
2    0.184358
3    0.184358
4    0.184047
1    0.181254
0    0.148976
5    0.117008
Name: count, dtype: float64

Let's convert our dependent variable into a 1-hot-encoded vector.

In [4]:
# Let's turn the target into a dummy vector
y_train = pd.get_dummies(train_df['label']).to_numpy(dtype='int64')
y_test = pd.get_dummies(test_df['label']).to_numpy(dtype='int64')

y_train[:10]

array([[0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0]])

# Problem 1: Bag-of-Words (BoW) Model [30 Points]

In this problem, we will build a bag-of-words model using the text vectorization capabilities of Keras. We will then change some of the parameters of this vectorization process and see how it changes the performance.



## Part (a): Build a Base Model [15 Points]

**Text Vectorization**

Please fill in the code in the following cell. We would like to create a text vectorization layer which uses:

* Maximum of 2000 tokens.
* Unigrams
* Outputs a multi-hot encoded BoW encoding
* Converts text to lower case and strips punctuation

In [5]:
# Set the maximum number of tokens (which is the size of the vocabulary) to 1000
max_tokens = 2000

# Configure the text vectorization layer
text_vectorization = keras.layers.TextVectorization(output_mode='multi_hot',max_tokens=max_tokens,standardize='lower_and_strip_punctuation', split='whitespace',ngrams=1)

# Let's adapt the Text Vectorization layer using the training corpus
text_vectorization.adapt(train_df['text'])

# We vectorize our input with the adapted Text Vectorization layer
X_train = text_vectorization(train_df['text'])
X_test = text_vectorization(test_df['text'])

pd.DataFrame(X_train, columns = text_vectorization.get_vocabulary())

,[UNK],the,of,to,a,and,in,is,i,that,...,loving,learning,jaegerbuphybuedu,hour,helps,glutamate,finding,delta,careful,bother
0,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,1,1,1,1,1,1,1,1,1,1,...,0,0,1,0,0,0,0,0,0,0
2,1,1,0,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
4,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3217,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3218,1,1,1,1,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3219,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3220,1,1,1,1,1,1,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
3221,1,1,1,1,1,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0

In the following cell, please build a simple Neural Network with a single hidden layer of 128 neurons and a ReLu activation function. Be sure to specify the shape of the input correctly and use the appropriate activation function for the output. Your model should have 256902 parameters. The code for compiling, training and computing the test accuracy has been written for you already.

In [22]:
### YOUR CODE BELOW ###
inputs = keras.layers.Input(shape=(max_tokens,))

x = keras.layers.Dense(128, activation='relu')(inputs)
outputs = keras.layers.Dense(y_train.shape[1], activation='softmax')(x)
### YOUR CODE ABOVE ###

bow_model = keras.Model(inputs, outputs)
bow_model.summary()

bow_model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy']
)

Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_2 (InputLayer)      │ (None, 2000)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 128)            │       256,128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 6)              │           774 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 256,902 (1003.52 KB)

 Trainable params: 256,902 (1003.52 KB)

 Non-trainable params: 0 (0.00 B)

A theme that we will be investigating in this homework is the **impact of the number of training examples on the various models**. As a result, in addition to training the model on all 3000+ training examples, we will also test how our model performs with only 200 examples.

The code below shows a fitting process in which we first fit model `bow_model` to the first 200 examples from the training set `(X_train[:200], y_train[:200]`). We print the accuracy of the model on the test set. Then, we run the training procedure for another 20 epochs, this time with the full data set `(X_train, y_train`).

In [23]:
bow_model.fit(
    x=X_train[:200], y=y_train[:200],
    epochs=20, batch_size=32,
    verbose=1,
)
print("\n*** Test accuracy with 200 Examples: %.4f ***\n" % bow_model.evaluate(x=X_test, y=y_test)[1])

bow_model.fit(
    x=X_train, y=y_train,
    epochs=20, batch_size=32,
    verbose=1,
)
print("\n*** Test accuracy with All Examples % .4f ***\n" % bow_model.evaluate(x=X_test, y=y_test)[1])

Epoch 1/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 2s 74ms/step - accuracy: 0.3350 - loss: 1.7121
Epoch 2/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9150 - loss: 1.1147
Epoch 3/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9800 - loss: 0.7378
Epoch 4/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9900 - loss: 0.4665
Epoch 5/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.2910
Epoch 6/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1827
Epoch 7/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1176
Epoch 8/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0789
Epoch 9/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0556
Epoch 10/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0411
Epoch 11/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0317
Epoch 12/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0253
Epoch 13/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0209
Epoch 14/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0176
Epoch 15/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0151
Epoch 16/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0131
Epoch 17/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0115
Epoch 18/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0102
Epoch 19/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0092
Epoch 20/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0082
68/68 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.6238 - loss: 1.0125

*** Test accuracy with 200 Examples: 0.6238 ***

Epoch 1/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.8631 - loss: 0.4338
Epoch 2/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9780 - loss: 0.1055
Epoch 3/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9922 - loss: 0.0536
Epoch 4/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9984 - loss: 0.0297
Epoch 5/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9997 - loss: 0.0185
Epoch 6/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0129
Epoch 7/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0095
Epoch 8/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0073
Epoch 9/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0058
Epoch 10/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0047
Epoch 11/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0039
Epoch 12/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0032
Epoch 13/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0028
Epoch 14/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0024
Epoch 15/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0020
Epoch 16/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0018
Epoch 17/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0016
Epoch 18/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0014
Epoch 19/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0012
Epoch 20/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0011
68/68 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8284 - loss: 0.7003

*** Test accuracy with All Examples  0.8284 ***

Please write down the test accuracy shown above and comment on the model's performance. What is the baseline performance by predicting the most frequent class?

**<font color='red'>Answer:</font>**

BoW Base Model
* Accuracy with 200 Examples: 63%.0%
* Accuracy with All Examples: 83.0%

Baseline in this case is around 17%. With fewer examples we achieve accuracy of about 63%. This is obviously corrected by using more examples and took it huge jump to 80%.

## Part (b): Exploring Hyperparameters [15 Points]

Now, let us try changing some of the hyperparameters that in the text vectorization process.

For each of the following modifications, please change the code for Problem 1(a), train the model and report the out-of-sample accuracy below. You do not need to duplicate the code from 1(a) here.

* Use bigrams instead of unigrams.
* Increase the maximum number of tokens from 2000 to 5000
* Use count vectorization instead of multi-hot.

Note that you should make each change independent of the other two changes. <font color='red'>Don't forget to undo each change before making the next </font>

Copy and paste the code from Problem 1(a) into a single cell. Then, make each of the 3 changes above and fill in the table of accuracies.

In [24]:
max_tokens = 2000

text_vectorization = keras.layers.TextVectorization(output_mode='multi_hot',
                                                    max_tokens=max_tokens,
                                                    standardize='lower_and_strip_punctuation',
                                                    split='whitespace',ngrams=2
)

text_vectorization.adapt(train_df['text'])

X_train = text_vectorization(train_df['text'])
X_test = text_vectorization(test_df['text'])

### YOUR CODE BELOW ###
inputs = keras.Input(shape=(max_tokens,))
x = keras.layers.Dense(128, activation='relu')(inputs)

outputs = keras.layers.Dense(y_train.shape[1], activation='softmax')(x)
### YOUR CODE ABOVE ###

bow_model = keras.Model(inputs, outputs)
bow_model.summary()

bow_model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy']
)

bow_model.fit(
    x=X_train[:200], y=y_train[:200],
    epochs=20, batch_size=32,
    verbose=1,
)
print("\n*** Test accuracy with 200 Examples: %.4f ***\n" % bow_model.evaluate(x=X_test, y=y_test)[1])

bow_model.fit(
    x=X_train, y=y_train,
    epochs=20, batch_size=32,
    verbose=1,
)
print("\n*** Test accuracy with All Examples % .4f ***\n" % bow_model.evaluate(x=X_test, y=y_test)[1])

Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_3 (InputLayer)      │ (None, 2000)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 128)            │       256,128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 6)              │           774 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 256,902 (1003.52 KB)

 Trainable params: 256,902 (1003.52 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 2s 74ms/step - accuracy: 0.2300 - loss: 1.7806
Epoch 2/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8700 - loss: 1.0853
Epoch 3/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9900 - loss: 0.6906
Epoch 4/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.4275
Epoch 5/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2626
Epoch 6/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.1636
Epoch 7/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1053
Epoch 8/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0711
Epoch 9/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0506
Epoch 10/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0379
Epoch 11/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0296
Epoch 12/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0239
Epoch 13/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0199
Epoch 14/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0169
Epoch 15/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0145
Epoch 16/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0127
Epoch 17/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0112
Epoch 18/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0099
Epoch 19/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0089
Epoch 20/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0080
68/68 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.5669 - loss: 1.1709

*** Test accuracy with 200 Examples: 0.5669 ***

Epoch 1/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.8206 - loss: 0.5260
Epoch 2/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9687 - loss: 0.1298
Epoch 3/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9907 - loss: 0.0668
Epoch 4/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9975 - loss: 0.0392
Epoch 5/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9991 - loss: 0.0245
Epoch 6/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9991 - loss: 0.0169
Epoch 7/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0125
Epoch 8/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0096
Epoch 9/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0076
Epoch 10/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0062
Epoch 11/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0051
Epoch 12/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0043
Epoch 13/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0036
Epoch 14/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0031
Epoch 15/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0027
Epoch 16/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0023
Epoch 17/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0020
Epoch 18/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0018
Epoch 19/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0016
Epoch 20/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0014
68/68 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7837 - loss: 0.9394

*** Test accuracy with All Examples  0.7837 ***

In [25]:
max_tokens = 5000

text_vectorization = keras.layers.TextVectorization(output_mode='multi_hot',
                                                    max_tokens=max_tokens,
                                                    standardize='lower_and_strip_punctuation',
                                                    split='whitespace',ngrams=1
)

text_vectorization.adapt(train_df['text'])

X_train = text_vectorization(train_df['text'])
X_test = text_vectorization(test_df['text'])

### YOUR CODE BELOW ###
inputs = keras.Input(shape=(max_tokens,))
x = keras.layers.Dense(128, activation='relu')(inputs)

outputs = keras.layers.Dense(y_train.shape[1], activation='softmax')(x)
### YOUR CODE ABOVE ###

bow_model = keras.Model(inputs, outputs)
bow_model.summary()

bow_model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy']
)

bow_model.fit(
    x=X_train[:200], y=y_train[:200],
    epochs=20, batch_size=32,
    verbose=1,
)
print("\n*** Test accuracy with 200 Examples: %.4f ***\n" % bow_model.evaluate(x=X_test, y=y_test)[1])

bow_model.fit(
    x=X_train, y=y_train,
    epochs=20, batch_size=32,
    verbose=1,
)
print("\n*** Test accuracy with All Examples % .4f ***\n" % bow_model.evaluate(x=X_test, y=y_test)[1])

Model: "functional_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_4 (InputLayer)      │ (None, 5000)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 128)            │       640,128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 6)              │           774 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 640,902 (2.44 MB)

 Trainable params: 640,902 (2.44 MB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 2s 91ms/step - accuracy: 0.3150 - loss: 1.7298
Epoch 2/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9900 - loss: 0.9621
Epoch 3/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.5296
Epoch 4/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.2725
Epoch 5/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.1412
Epoch 6/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0780
Epoch 7/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0469
Epoch 8/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0309
Epoch 9/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0221
Epoch 10/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0168
Epoch 11/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0134
Epoch 12/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0111
Epoch 13/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0094
Epoch 14/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0082
Epoch 15/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0072
Epoch 16/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0064
Epoch 17/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0057
Epoch 18/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0051
Epoch 19/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0047
Epoch 20/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0043
68/68 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.6550 - loss: 0.9547

*** Test accuracy with 200 Examples: 0.6550 ***

Epoch 1/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.8991 - loss: 0.3401
Epoch 2/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9950 - loss: 0.0445
Epoch 3/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9997 - loss: 0.0189
Epoch 4/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9997 - loss: 0.0111
Epoch 5/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0075
Epoch 6/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0054
Epoch 7/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0041
Epoch 8/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0032
Epoch 9/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0025
Epoch 10/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0021
Epoch 11/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0017
Epoch 12/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0015
Epoch 13/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0013
Epoch 14/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0011
Epoch 15/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 9.4090e-04
Epoch 16/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 8.2508e-04
Epoch 17/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 7.2786e-04
Epoch 18/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 6.4595e-04
Epoch 19/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 5.7600e-04
Epoch 20/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 5.1582e-04
68/68 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8732 - loss: 0.5000

*** Test accuracy with All Examples  0.8732 ***

In [26]:
max_tokens = 2000

text_vectorization = keras.layers.TextVectorization(output_mode='count',
                                                    max_tokens=max_tokens,
                                                    standardize='lower_and_strip_punctuation',
                                                    split='whitespace',ngrams=1
)

text_vectorization.adapt(train_df['text'])

X_train = text_vectorization(train_df['text'])
X_test = text_vectorization(test_df['text'])

### YOUR CODE BELOW ###
inputs = keras.Input(shape=(max_tokens,))
x = keras.layers.Dense(128, activation='relu')(inputs)

outputs = keras.layers.Dense(y_train.shape[1], activation='softmax')(x)
### YOUR CODE ABOVE ###

bow_model = keras.Model(inputs, outputs)
bow_model.summary()

bow_model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy']
)

bow_model.fit(
    x=X_train[:200], y=y_train[:200],
    epochs=20, batch_size=32,
    verbose=1,
)
print("\n*** Test accuracy with 200 Examples: %.4f ***\n" % bow_model.evaluate(x=X_test, y=y_test)[1])

bow_model.fit(
    x=X_train, y=y_train,
    epochs=20, batch_size=32,
    verbose=1,
)
print("\n*** Test accuracy with All Examples % .4f ***\n" % bow_model.evaluate(x=X_test, y=y_test)[1])

Model: "functional_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_5 (InputLayer)      │ (None, 2000)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 128)            │       256,128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 6)              │           774 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 256,902 (1003.52 KB)

 Trainable params: 256,902 (1003.52 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 2s 72ms/step - accuracy: 0.2400 - loss: 2.2523
Epoch 2/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5700 - loss: 1.3254
Epoch 3/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7600 - loss: 0.9235
Epoch 4/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9650 - loss: 0.5707
Epoch 5/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9900 - loss: 0.4311
Epoch 6/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.3078
Epoch 7/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.2287
Epoch 8/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1725
Epoch 9/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1323
Epoch 10/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1032
Epoch 11/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0819
Epoch 12/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0657
Epoch 13/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0533
Epoch 14/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0438
Epoch 15/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0363
Epoch 16/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0302
Epoch 17/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0253
Epoch 18/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0212
Epoch 19/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0179
Epoch 20/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0153
68/68 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.6191 - loss: 1.1956

*** Test accuracy with 200 Examples: 0.6191 ***

Epoch 1/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8243 - loss: 0.7230
Epoch 2/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9469 - loss: 0.2153
Epoch 3/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9745 - loss: 0.1226
Epoch 4/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9888 - loss: 0.0768
Epoch 5/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0504
Epoch 6/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9981 - loss: 0.0332
Epoch 7/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9997 - loss: 0.0235
Epoch 8/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0166
Epoch 9/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0121
Epoch 10/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0089
Epoch 11/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0068
Epoch 12/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0052
Epoch 13/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0041
Epoch 14/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0032
Epoch 15/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0025
Epoch 16/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0020
Epoch 17/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0017
Epoch 18/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0014
Epoch 19/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0011
Epoch 20/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 9.7076e-04
68/68 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8322 - loss: 0.9496

*** Test accuracy with All Examples  0.8322 ***

Replace the following numbers with the out-of-sample accuracy you obtained from re-running Problem 1(a)'s code with the relevant modifications.

For each of the 3 modifications, discuss why one might expect such a change to be beneficial to the model's out-of-sample accuracy.

Using the actual accuracies, comment on whether each modification improved, hurt or didn't affect accuracy from the baseline model in (a).

**<font color='red'>Answer:</font>**

* Bigrams instead of unigrams
  * 200 Training Examples: 55.5%
  * All Training Examples: 77.5%
  * **Discussion**: Adding `ngrams=2` i.e. bigrams doesn't really increases the accuracy rather it decreases it. Possible reason behind this is that because we are not increassing the `max_tokens` size although we are doing word pairing so many possible context is lost because of unnecessary pairs like e.g. 'on the' which do not contribute for the training of model.
* Increasing max_tokens to 5000.
  * 200 Training Examples: 66.6%
  * All Training Examples: 86.9%
  * **Discussion**: Accuracy is incresed 4% because of increase in tokens since context was added which was left out due to some tokens which were exceeding the limit in earlier model.
* Count instead of multi-hot
  * 200 Training Examples: 62.4%
  * All Training Examples: 83.1%
  * **Discussion**: This almost stays the same. Possible reason behind this is `count` will affect if frequency of word affects class. E.g. Sentiment Analysis, whichever type i.e. +ve or -ve word affects the sentiment of sentence.

# Problem 2: GloVe without Fine-Tuning [20 Points]

Now, we will train a model using GloVe. We will try using GloVe vectors out of box and with fine-tuning. Let's first download the GloVe vectors from the internet.

In [27]:
!wget -O glove.6B.300d.zip https://www.dropbox.com/scl/fi/ree568j1h690ktpcn729b/glove.6B.300d.zip?rlkey=eq9r67js0n0vm2znvdev9rerf&dl=1
!unzip glove.6B.300d.zip

--2026-10-11 06:10:29--  https://www.dropbox.com/scl/fi/ree568j1h690ktpcn729b/glove.6B.300d.zip?rlkey=eq9r67js0n0vm2znvdev9rerf
Resolving www.dropbox.com (www.dropbox.com)... 162.125.81.18, 2620:100:6031:18::a27d:5112
Connecting to www.dropbox.com (www.dropbox.com)|162.125.81.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://uc959e4681a98203657968cd4421.dl.dropboxusercontent.com/cd/0/inline/DJyJZAnHNPN_asZeiFOIoTLGKlq3vSeGO3Cj9OBhuj7bB3VynAx1zjhBID7kT1UWtJXO-P9vuQ3VDOucspadnFUkh_zHd96GsQNXinT0pyGLU96c21y7azE6bvnOjc_aTsrSySAyW-UlwpsNJZ4qKxmN/file# [following]
--2026-10-11 06:10:29--  https://uc959e4681a98203657968cd4421.dl.dropboxusercontent.com/cd/0/inline/DJyJZAnHNPN_asZeiFOIoTLGKlq3vSeGO3Cj9OBhuj7bB3VynAx1zjhBID7kT1UWtJXO-P9vuQ3VDOucspadnFUkh_zHd96GsQNXinT0pyGLU96c21y7azE6bvnOjc_aTsrSySAyW-UlwpsNJZ4qKxmN/file
Resolving uc959e4681a98203657968cd4421.dl.dropboxusercontent.com (uc959e4681a98203657968cd4421.dl.dropboxusercontent.com)... 162.125.81.15, 2620:100:6031:15::a27d:510f
Connecting to uc959e4681a98203657968cd4421.dl.dropboxusercontent.com (uc959e4681a98203657968cd4421.dl.dropboxusercontent.com)|162.125.81.15|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /cd/0/inline2/DJz0Gz-VKeWvcbuIpkZEM5HS0BnPv8M9fWipY_guYgAURJzfCvYK6OQJlswhWVsOdFD4E73ffKRV8UgckmVMczeVYntrmF-i8viHUKlI3NsH4kHwJwFjAx_klpePIAkL79oC_E1L5OFkxBSXNvp-Z8S7KbQu8jvxFP7wUl424rKfy9z2Z1WjSzZQdrNUgtJiBdx0eEHr_eXoFikHmKleJH9lPFklhMDbFb7IzSFFS59FJaOrCmbCc6MPWKpPmLGFK0RAzq4713ZoW0cmiZ-vBxwuElppoIAnJSwa7XInEz5AI9QGGNdmHUAWAJfD-mPTekh3y2aGWZHxlarBaAgKP7nno8Iw-qMnDi5DAcDWEclI5xhxzwRQ99yStI0EBU55kBk/file [following]
--2026-10-11 06:10:30--  https://uc959e4681a98203657968cd4421.dl.dropboxusercontent.com/cd/0/inline2/DJz0Gz-VKeWvcbuIpkZEM5HS0BnPv8M9fWipY_guYgAURJzfCvYK6OQJlswhWVsOdFD4E73ffKRV8UgckmVMczeVYntrmF-i8viHUKlI3NsH4kHwJwFjAx_klpePIAkL79oC_E1L5OFkxBSXNvp-Z8S7KbQu8jvxFP7wUl424rKfy9z2Z1WjSzZQdrNUgtJiBdx0eEHr_eXoFikHmKleJH9lPFklhMDbFb7IzSFFS59FJaOrCmbCc6MPWKpPmLGFK0RAzq4713ZoW0cmiZ-vBxwuElppoIAnJSwa7XInEz5AI9QGGNdmHUAWAJfD-mPTekh3y2aGWZHxlarBaAgKP7nno8Iw-qMnDi5DAcDWEclI5xhxzwRQ99yStI0EBU55kBk/file
Reusing existing connection to uc959e4681a98203657968cd4421.dl.dropboxusercontent.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 359766655 (343M) [application/zip]
Saving to: ‘glove.6B.300d.zip’

glove.6B.300d.zip   100%[===================>] 343.10M  21.7MB/s    in 17s

2026-10-11 06:10:47 (20.8 MB/s) - ‘glove.6B.300d.zip’ saved [359766655/359766655]

Archive:  glove.6B.300d.zip
replace glove.6B.300d.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename:

## Part (a): Load Pre-trained Vectors [10 Points]

Let's take the `glove.6B.300d.txt` file, which consists of 300-dimensional vectors for 400,000 words in English.

In [28]:
embedding_dim = 300
path_to_glove_file = f"glove.6B.{embedding_dim}d.txt"

embeddings_index = {}
with open(path_to_glove_file) as f:
    for line in f:
        word, coefs = line.split(maxsplit=1)
        coefs = np.fromstring(coefs, "f", sep=" ")
        embeddings_index[word] = coefs

print(f"Found {len(embeddings_index)} word vectors.")

Found 400000 word vectors.

For any of thes 400,000 words, we can query its 300-dimensional vector

In [29]:
embeddings_index['hello']

array([-3.3712e-01, -2.1691e-01, -6.6365e-03, -4.1625e-01, -1.2555e+00,
       -2.8466e-02, -7.2195e-01, -5.2887e-01,  7.2085e-03,  3.1997e-01,
        2.9425e-02, -1.3236e-02,  4.3511e-01,  2.5716e-01,  3.8995e-01,
       -1.1968e-01,  1.5035e-01,  4.4762e-01,  2.8407e-01,  4.9339e-01,
        6.2826e-01,  2.2888e-01, -4.0385e-01,  2.7364e-02,  7.3679e-03,
        1.3995e-01,  2.3346e-01,  6.8122e-02,  4.8422e-01, -1.9578e-02,
       -5.4751e-01, -5.4983e-01, -3.4091e-02,  8.0017e-03, -4.3065e-01,
       -1.8969e-02, -8.5670e-02, -8.1123e-01, -2.1080e-01,  3.7784e-01,
       -3.5046e-01,  1.3684e-01, -5.5661e-01,  1.6835e-01, -2.2952e-01,
       -1.6184e-01,  6.7345e-01, -4.6597e-01, -3.1834e-02, -2.6037e-01,
       -1.7797e-01,  1.9436e-02,  1.0727e-01,  6.6534e-01, -3.4836e-01,
        4.7833e-02,  1.6440e-01,  1.4088e-01,  1.9204e-01, -3.5009e-01,
        2.6236e-01,  1.7626e-01, -3.1367e-01,  1.1709e-01,  2.0378e-01,
        6.1775e-01,  4.9075e-01, -7.5210e-02, -1.1815e-01,  1.8685e-01,
        4.0679e-01,  2.8319e-01, -1.6290e-01,  3.8388e-02,  4.3794e-01,
        8.8224e-02,  5.9046e-01, -5.3515e-02,  3.8819e-02,  1.8202e-01,
       -2.7599e-01,  3.9474e-01, -2.0499e-01,  1.7411e-01,  1.0315e-01,
        2.5117e-01, -3.6542e-01,  3.6528e-01,  2.2448e-01, -9.7551e-01,
        9.4505e-02, -1.7859e-01, -3.0688e-01, -5.8633e-01, -1.8526e-01,
        3.9565e-02, -4.2309e-01, -1.5715e-01,  2.0401e-01,  1.6906e-01,
        3.4465e-01, -4.2262e-01,  1.9553e-01,  5.9454e-01, -3.0531e-01,
       -1.0633e-01, -1.9055e-01, -5.8544e-01,  2.1357e-01,  3.8414e-01,
        9.1499e-02,  3.8353e-01,  2.9075e-01,  2.4519e-02,  2.8440e-01,
        6.3715e-02, -1.5483e-01,  4.0031e-01,  3.1543e-01, -3.7128e-02,
        6.3363e-02, -2.7090e-01,  2.5160e-01,  4.7105e-01,  4.9556e-01,
       -3.6401e-01,  1.0370e-01,  4.6076e-02,  1.6565e-01, -2.9024e-01,
       -6.6949e-02, -3.0881e-01,  4.8263e-01,  3.0972e-01, -1.1145e-01,
       -1.0329e-01,  2.8585e-02, -1.3579e-01,  5.2924e-01, -1.4077e-01,
        9.1763e-02,  1.3127e-01, -2.0944e-01,  2.2327e-02, -7.7692e-02,
        7.7934e-02, -3.3067e-02,  1.1680e-01,  3.2029e-01,  3.7749e-01,
       -7.5679e-01, -1.5944e-01,  1.4964e-01,  4.2253e-01,  2.8136e-03,
        2.1328e-01,  8.6776e-02, -5.2704e-02, -4.0859e-01, -1.1774e-01,
        9.0621e-02, -2.3794e-01, -1.8326e-01,  1.3115e-01, -5.5949e-01,
        9.2071e-02, -3.9504e-02,  1.3334e-01,  4.9632e-01,  2.8733e-01,
       -1.8544e-01,  2.4618e-02, -4.2826e-01,  7.4148e-02,  7.6584e-04,
        2.3950e-01,  2.2615e-01,  5.5166e-02, -7.5096e-02, -2.2308e-01,
        2.3775e-01, -4.5455e-01,  2.6564e-01, -1.5137e-01, -2.4146e-01,
       -2.4736e-01,  5.5214e-01,  2.6819e-01,  4.8831e-01, -1.3423e-01,
       -1.5918e-01,  3.7606e-01, -1.9834e-01,  1.6699e-01, -1.5368e-01,
        2.4561e-01, -9.2506e-02, -3.0257e-01, -2.9493e-01, -7.4917e-01,
        1.0567e+00,  3.7971e-01,  6.9314e-01, -3.1672e-02,  2.1588e-01,
       -4.0739e-01, -1.5264e-01,  3.2296e-01, -1.2999e-01, -5.0129e-01,
       -4.4231e-01,  1.6904e-02, -1.1459e-02,  7.2293e-03,  1.1026e-01,
        2.1568e-01, -3.2373e-01, -3.7292e-01, -9.2456e-03, -2.6769e-01,
        3.9066e-01,  3.5742e-01, -6.0632e-02,  6.7966e-02,  3.3830e-01,
        6.5747e-02,  1.5794e-01,  4.7155e-02,  2.3682e-01, -9.1370e-02,
        6.4649e-01, -2.5491e-01, -6.7940e-01, -6.9752e-01, -1.0145e-01,
       -3.6255e-01,  3.6967e-01, -4.1295e-01,  8.2724e-02, -3.5053e-01,
       -1.7564e-01,  8.5095e-02, -5.7724e-01,  5.0252e-01,  5.2180e-01,
        5.7327e-02, -7.9754e-01, -3.7770e-01,  7.8149e-01,  2.4597e-01,
        6.0672e-01, -2.0082e-01, -3.8792e-01,  4.1295e-01, -1.6143e-01,
        1.0427e-02,  4.3197e-01,  4.6297e-03,  2.1185e-01, -2.6606e-01,
       -5.8740e-02, -5.1003e-01,  2.8524e-01,  1.3627e-02, -2.7346e-01,
        6.1848e-02, -5.7901e-01, -5.1136e-01,  3.6382e-01,  3.5144e-01,
       -1.6501e-01, -4.6041e-01, -6.4742e-02, -6.8310e-01, -4.7427e-02,
        1.5861e-01, -4.7288e-01,  3.3968e-01,  1.2092e-03,  1.6018e-01,
       -5.8024e-01,  1.4556e-01, -9.1317e-01, -3.7592e-01, -3.2950e-01,
        5.3465e-01,  1.8224e-01, -5.2265e-01, -2.6209e-01, -4.2458e-01,
       -1.8034e-01,  9.9502e-02, -1.5114e-01, -6.6731e-01,  2.4483e-01,
       -5.6630e-01,  3.3843e-01,  4.0558e-01,  1.8073e-01,  6.4250e-01],
      dtype=float32)

Let's create our vocabulary space from the training data. We do this using the `TextVectorization` layer just like before. However, this time, we choose `output_mode=int`.

In [30]:
max_length = 400 # For each piece of text, consider only the first 400 tokens (then truncate or pad)
max_tokens = 2000 # Our vocabulary space of tokens can be at most size 5000

text_vectorization_glove = keras.layers.TextVectorization(
    max_tokens=max_tokens,
    output_mode="int",
    output_sequence_length=max_length,
)

text_vectorization_glove.adapt(train_df['text'])

X_train_glove = text_vectorization_glove(train_df['text'])
X_test_glove = text_vectorization_glove(test_df['text'])

X_train_glove

<tf.Tensor: shape=(3222, 400), dtype=int64, numpy=
array([[  14,    1,    1, ...,    0,    0,    0],
       [  14,    1, 1334, ...,  726,    1,    1],
       [  14,    1,    1, ...,    0,    0,    0],
       ...,
       [  14,    1,   27, ...,  116,    1,    6],
       [  14,  546,  325, ...,    0,    0,    0],
       [  14,    1,    1, ...,    0,    0,    0]])>

In the output above for `X_train_glove`, each row is a training example and the columns represent the _index_ of the token. For example, the first training example starts with token 14, followed by token 1, then token 1,... and ending with the padding tokens 0.

**Question**: What English word does token 14 correspond to? Hint: A cell from the Introduction will help you here.

<font color='red'>**Answer:**</font>

Every one of sentences above are starting as `From: someone@gmail.com`. So, here you can conclude that 14 represent the word `From` since each vector in `X_train_glove` is also starting with 14.

For each of the 2000 tokens we extracted from our training data, we will look up its vector from `embedding_vector`.

In [31]:
vocabulary = text_vectorization_glove.get_vocabulary()
word_index = dict(zip(vocabulary, range(len(vocabulary))))

counter = 0
embedding_matrix = np.zeros((max_tokens, embedding_dim))
for word, i in word_index.items():
    if i < max_tokens:
        embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector
    else:
        counter += 1

embedding_matrix

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.04656   ,  0.21318001, -0.0074364 , ...,  0.0090611 ,
        -0.20988999,  0.053913  ],
       ...,
       [-0.038683  ,  0.32398999,  0.10977   , ...,  0.10819   ,
        -0.22115   , -0.17591   ],
       [ 0.47946   ,  0.23098999, -0.11539   , ..., -0.26082999,
        -0.30032   ,  0.089238  ],
       [ 0.19551   , -0.24070001,  0.36401001, ..., -0.069489  ,
         0.32620001,  0.099097  ]])

The above matrix is of shape 2000 by 300. Each row corresponds to one of the 2000 tokens and the value in the row is the 300-dimensional vectorization of that token. We notice that the first two tokens above (index 0 and index 1) are mapped to the all zeros vector.

**Question:** What tokens are represented by index 0 and index 1?

<font color='red'>**Answer:**</font>

Index 0 = `[PAD]`

Index 1 = `[UNK]`

## Part (b): Build the Model [10 Points]
Now, let's build the model. Fill in the missing code below.

* Create an embedding layer of the appropriate input and output dimensions. Initialize it to `keras.initializers.Constant(embedding_matrix)`, set `trainable=False` and `mask_zero=True`.
* Add a `GlobalAveragePooling1D` layer.
* Followed by a Dense layer with 128 neurons (ReLU activation), then a Dropout layer with probability of dropout 0.2. Follow this by another Dense layer of 128 neurons and a Dropout with 0.2 probability.


Your model should have 655,814 parameters out of which 55,814 are trainable.

In [32]:
embedding_layer = keras.layers.Embedding(max_tokens, embedding_dim,embeddings_initializer=keras.initializers.Constant(embedding_matrix), trainable=False, mask_zero=True)

### YOUR CODE BELOW ###
inputs = keras.Input(shape=(max_length,))
x = embedding_layer(inputs)
x = keras.layers.GlobalAveragePooling1D()(x)
x = keras.layers.Dense(128, activation='relu')(x)
x = keras.layers.Dropout(0.2)(x)
x = keras.layers.Dense(128, activation='relu')(x)
x = keras.layers.Dropout(0.2)(x)

outputs = keras.layers.Dense(y_train.shape[1], activation='softmax')(x)
### YOUR CODE ABOVE ###

glove_model = keras.Model(inputs, outputs)
glove_model.summary()

# Compile model using Adam
glove_model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy']
)

# Fit model on the training data with 10 epochs and batch size of 32
glove_model.fit(
    x=X_train_glove[:200], y=y_train[:200],
    epochs=20, batch_size=32,
    verbose=1,
)

print("\n*** Test accuracy with 200 Examples: %.3f ***\n" % glove_model.evaluate(x=X_test_glove, y=y_test)[1])

# Fit model on the training data with 10 epochs and batch size of 32
glove_model.fit(
    x=X_train_glove, y=y_train,
    epochs=20, batch_size=32,
    verbose=1,
)

print("\n*** Test accuracy with All Examples: %.3f ***\n" % glove_model.evaluate(x=X_test_glove, y=y_test)[1])

Model: "functional_6"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_6       │ (None, 400)       │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_1         │ (None, 400, 300)  │    600,000 │ input_layer_6[0]… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ not_equal           │ (None, 400)       │          0 │ input_layer_6[0]… │
│ (NotEqual)          │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ global_average_poo… │ (None, 300)       │          0 │ embedding_1[0][0… │
│ (GlobalAveragePool… │                   │            │ not_equal[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_12 (Dense)    │ (None, 128)       │     38,528 │ global_average_p… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout (Dropout)   │ (None, 128)       │          0 │ dense_12[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_13 (Dense)    │ (None, 128)       │     16,512 │ dropout[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_1 (Dropout) │ (None, 128)       │          0 │ dense_13[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_14 (Dense)    │ (None, 6)         │        774 │ dropout_1[0][0]   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 655,814 (2.50 MB)

 Trainable params: 55,814 (218.02 KB)

 Non-trainable params: 600,000 (2.29 MB)

Epoch 1/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 5s 277ms/step - accuracy: 0.2100 - loss: 1.7878
Epoch 2/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2350 - loss: 1.7625
Epoch 3/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2750 - loss: 1.7431
Epoch 4/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3100 - loss: 1.7192
Epoch 5/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3400 - loss: 1.7196
Epoch 6/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3250 - loss: 1.6905
Epoch 7/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3800 - loss: 1.6598
Epoch 8/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3800 - loss: 1.6199
Epoch 9/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4400 - loss: 1.5804
Epoch 10/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4250 - loss: 1.5437
Epoch 11/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5050 - loss: 1.4974
Epoch 12/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5250 - loss: 1.4436
Epoch 13/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5550 - loss: 1.3842
Epoch 14/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5700 - loss: 1.3342
Epoch 15/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5900 - loss: 1.2637
Epoch 16/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6500 - loss: 1.1933
Epoch 17/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6550 - loss: 1.1470
Epoch 18/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6650 - loss: 1.1070
Epoch 19/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6450 - loss: 1.0765
Epoch 20/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6950 - loss: 1.0091
68/68 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.6200 - loss: 1.1191

*** Test accuracy with 200 Examples: 0.620 ***

Epoch 1/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.6760 - loss: 0.9273
Epoch 2/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7498 - loss: 0.6922
Epoch 3/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7765 - loss: 0.5978
Epoch 4/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7948 - loss: 0.5476
Epoch 5/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8038 - loss: 0.5164
Epoch 6/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8197 - loss: 0.4812
Epoch 7/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8302 - loss: 0.4606
Epoch 8/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8327 - loss: 0.4389
Epoch 9/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8405 - loss: 0.4264
Epoch 10/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8532 - loss: 0.3995
Epoch 11/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8541 - loss: 0.3919
Epoch 12/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8579 - loss: 0.3726
Epoch 13/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8662 - loss: 0.3615
Epoch 14/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8665 - loss: 0.3489
Epoch 15/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8759 - loss: 0.3347
Epoch 16/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8824 - loss: 0.3205
Epoch 17/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8827 - loss: 0.3195
Epoch 18/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8873 - loss: 0.2961
Epoch 19/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8945 - loss: 0.2875
Epoch 20/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8886 - loss: 0.3031
68/68 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7869 - loss: 0.6068

*** Test accuracy with All Examples: 0.787 ***

Report the performance of our Glove Model above which uses the pre-trained word embeddings without fine-tuning. Comment on this performance. Please propose an explanation for why you think GloVe did not perform as well as BoW.

**<font color='red'>Your Answer Here</font>**

* 200 Examples: 63.0%
* All Examples: 80.0%

_Please replace this text with your response_.

# Problem 3: GloVe with Fine Tuning [30 Points]

In problem 2, we did not fine-tune the word embeddings from GloVe. We simply downloaded them from the internet and used them as-is. In this question, we will fine-tune the embeddings to the training data set.

## Part (a): Why Fine Tuning is Needed [10 Points]

The goal of this part is to motivate why fine tuning of the word embeddings is necessary. In the process, we will understand why BoW is able to perform so well over GloVe.

The 20-newsgroup dataset consists of posts from a news discussion forum (from back in the day). Each of these posts look like an email, with a From: someone@email.com and subject lines. This is called the **header** of the post. Similarly, the email also has a **footer**, which typically consists of the author's name and affiliation. Consider one of the training examples shown below:

In [33]:
print(train_df['text'][2101])

From: henry@zoo.toronto.edu (Henry Spencer)
Subject: Re: HLV for Fred (was Re: Prefab Space Station?)
Article-I.D.: zoo.C51875.67p
Organization: U of Toronto Zoology
Lines: 28

In article <C5133A.Gzx@news.cso.uiuc.edu> jbh55289@uxa.cso.uiuc.edu (Josh Hopkins) writes:
>>>Titan IV launches ain't cheap
>>Granted. But that's because titan IV's are bought by the governemnt. Titan
>>III is actually the cheapest way to put a pound in space of all US expendable
>>launchers.
>
>In that case it's rather ironic that they are doing so poorly on the commercial
>market.  Is there a single Titan III on order?

The problem with Commercial Titan is that MM has made little or no attempt
to market it.  They're basically happy with their government business and
don't want to have to learn how to sell commercially.

A secondary problem is that it is a bit big.  They'd need to go after
multi-satellite launches, a la Ariane, and that complicates the marketing
task quite significantly.

They also had some problems with launch facilities at just the wrong time
to get them started properly.  If memory serves, the pad used for the Mars
Observer launch had just come out of heavy refurbishment work that had
prevented launches from it for a year or so.

There have been a few CT launches.  Mars Observer was one of them.  So
was that stranded Intelsat, and at least one of its brothers that reached
orbit properly.
--
All work is one man's work.             | Henry Spencer @ U of Toronto Zoology
                    - Kipling           |  henry@zoo.toronto.edu  utzoo!henry

The header would be

```
From: henry@zoo.toronto.edu (Henry Spencer)
Subject: Re: HLV for Fred (was Re: Prefab Space Station?)
Article-I.D.: zoo.C51875.67p
Organization: U of Toronto Zoology
Lines: 28
```

and the footer is

```
All work is one man's work.             | Henry Spencer @ U of Toronto Zoology
                    - Kipling           |  henry@zoo.toronto.edu  utzoo!henry
```

Note that this document belongs to the topic **sci.space** (i.e. astronomy).

Recall the text vectorization layer from Problem 1(a). An interesting token that appears in our vocabulary space is the token `henryzootorontoedu`, appearing at index 1121. This token also appears in the example text above.

In [34]:
idx = text_vectorization_glove.get_vocabulary().index('henryzootorontoedu')
print('Token number %d is henryzootorontoedu' % idx)

Token number 1121 is henryzootorontoedu

This token actually appears in quite a few of the training examples. Notice that all of the labels of these documents is 4, corresponding to the category **sci.space**

In [35]:
train_df.loc[np.where(X_train_glove == idx)[0]]

                                                   text  label
211   From: keithley@apple.com (Craig Keithley)\nSub...      4
219   From: henry@zoo.toronto.edu (Henry Spencer)\nS...      4
271   From: henry@zoo.toronto.edu (Henry Spencer)\nS...      4
271   From: henry@zoo.toronto.edu (Henry Spencer)\nS...      4
274   From: sysmgr@king.eng.umd.edu (Doug Mohney)\nS...      4
...                                                 ...    ...
2874  From: dong@oakhill.sps.mot.com (Don M. Gibson)...      4
2960  From: henry@zoo.toronto.edu (Henry Spencer)\nS...      4
2960  From: henry@zoo.toronto.edu (Henry Spencer)\nS...      4
3197  From: Leigh Palmer <palmer@sfu.ca>\nSubject: R...      4
3207  From: John Lussmyer <dragon@angus.mi.org>\nSub...      4

[89 rows x 2 columns]

Looking at our GloVe embeddings, the embedding for `henryzootorontoedu` is the all zeros vector.

In [36]:
print('The embedding for token %d is' % idx, embedding_matrix[idx, :])

The embedding for token 1121 is [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Using the information above regarding this token `henryzootorontoedu`, please explain why BoW has an advantage of GloVe (with no fine-tuning). What do you think will happen to the embedding of `henryzootorontoedu` if we do perform fine-tuning?

<font color='red'>**Answer:**</font>

We see that `henryzootorontoedu` is highly correlated with sci-space. BoW model will learn this very quickly. On the other hand GloVe will not be able to detect this pattern as this `henryzootorontoedu` is not a part of GloVe embeddings so it will asign zero vector to it, but with fine tuning it may be able to achieve some sort of similar vector with the existing embeddings in the vocab.

## Part (b): Stripping the Header [10 Points]

It turns out that we can strip the header and footer from the training and testing examples pretty easily. For example, the same document above is now shown below:

In [37]:
newsgroups_train_raw = fetch_20newsgroups(subset='train', categories = ['alt.atheism', 'talk.religion.misc', 'comp.graphics', 'sci.space', 'sci.med', 'rec.autos'], remove=('headers', 'footers', 'quotes'))
newsgroups_test_raw = fetch_20newsgroups(subset='test', categories = ['alt.atheism', 'talk.religion.misc', 'comp.graphics', 'sci.space', 'sci.med', 'rec.autos'], remove=('headers', 'footers', 'quotes'))

train_df_raw = pd.DataFrame({'text': newsgroups_train_raw.data, 'label': newsgroups_train_raw.target})
test_df_raw = pd.DataFrame({'text': newsgroups_test_raw.data, 'label': newsgroups_test_raw.target})

print(train_df_raw['text'][2101])

The problem with Commercial Titan is that MM has made little or no attempt
to market it.  They're basically happy with their government business and
don't want to have to learn how to sell commercially.

A secondary problem is that it is a bit big.  They'd need to go after
multi-satellite launches, a la Ariane, and that complicates the marketing
task quite significantly.

They also had some problems with launch facilities at just the wrong time
to get them started properly.  If memory serves, the pad used for the Mars
Observer launch had just come out of heavy refurbishment work that had
prevented launches from it for a year or so.

There have been a few CT launches.  Mars Observer was one of them.  So
was that stranded Intelsat, and at least one of its brothers that reached
orbit properly.

Now, copy the code from Problem 1(a), to train a BoW model, but this time adapt the corpus and use `train_df_raw` and `test_df_raw` instead of `train_df` and `test_df`. Note that we name this model `bow_model_raw` instead of `bow_model`.

In [38]:
max_tokens = 2000

text_vectorization = keras.layers.TextVectorization(
    output_mode='multi_hot',max_tokens=max_tokens,standardize='lower_and_strip_punctuation', split='whitespace',ngrams=1
)

text_vectorization.adapt(train_df_raw['text'])

X_train_raw = text_vectorization(train_df_raw['text'])
X_test_raw = text_vectorization(test_df_raw['text'])

### YOUR CODE BELOW ###
inputs = keras.layers.Input(shape=(max_tokens,))

x = keras.layers.Dense(128, activation='relu')(inputs)
outputs = keras.layers.Dense(y_train.shape[1], activation='softmax')(x)
### YOUR CODE ABOVE ###

bow_model_raw = keras.Model(inputs, outputs)
bow_model_raw.summary()

bow_model_raw.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy']
)

bow_model_raw.fit(
    x=X_train_raw[:200], y=y_train[:200],
    epochs=20, batch_size=32,
    verbose=1,
)
print("\n*** Test accuracy with 200 Examples: %.4f ***\n" % bow_model_raw.evaluate(x=X_test_raw, y=y_test)[1])

bow_model_raw.fit(
    x=X_train_raw, y=y_train,
    epochs=20, batch_size=32,
    verbose=1,
)
print("\n*** Test accuracy with All Examples % .4f ***\n" % bow_model_raw.evaluate(x=X_test_raw, y=y_test)[1])

Model: "functional_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_7 (InputLayer)      │ (None, 2000)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 128)            │       256,128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 6)              │           774 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 256,902 (1003.52 KB)

 Trainable params: 256,902 (1003.52 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 2s 72ms/step - accuracy: 0.2200 - loss: 1.7559
Epoch 2/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7900 - loss: 1.3253
Epoch 3/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9000 - loss: 1.0499
Epoch 4/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9400 - loss: 0.8269
Epoch 5/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9500 - loss: 0.6539
Epoch 6/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9700 - loss: 0.5246
Epoch 7/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9750 - loss: 0.4284
Epoch 8/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9850 - loss: 0.3562
Epoch 9/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9850 - loss: 0.3016
Epoch 10/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9850 - loss: 0.2592
Epoch 11/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9850 - loss: 0.2259
Epoch 12/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9850 - loss: 0.1993
Epoch 13/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9850 - loss: 0.1779
Epoch 14/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9850 - loss: 0.1605
Epoch 15/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9850 - loss: 0.1462
Epoch 16/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9850 - loss: 0.1341
Epoch 17/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9850 - loss: 0.1240
Epoch 18/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9850 - loss: 0.1154
Epoch 19/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9850 - loss: 0.1080
Epoch 20/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9850 - loss: 0.1016
68/68 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.4923 - loss: 1.3592

*** Test accuracy with 200 Examples: 0.4923 ***

Epoch 1/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.6890 - loss: 0.8767
Epoch 2/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8659 - loss: 0.4263
Epoch 3/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9112 - loss: 0.3065
Epoch 4/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9373 - loss: 0.2404
Epoch 5/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9510 - loss: 0.1962
Epoch 6/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9597 - loss: 0.1655
Epoch 7/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9643 - loss: 0.1435
Epoch 8/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9677 - loss: 0.1270
Epoch 9/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9705 - loss: 0.1141
Epoch 10/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9714 - loss: 0.1047
Epoch 11/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9724 - loss: 0.0974
Epoch 12/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9727 - loss: 0.0918
Epoch 13/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9730 - loss: 0.0873
Epoch 14/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9739 - loss: 0.0838
Epoch 15/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9742 - loss: 0.0808
Epoch 16/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9742 - loss: 0.0785
Epoch 17/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9742 - loss: 0.0765
Epoch 18/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9742 - loss: 0.0749
Epoch 19/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9742 - loss: 0.0735
Epoch 20/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9742 - loss: 0.0724
68/68 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6723 - loss: 1.5712

*** Test accuracy with All Examples  0.6723 ***

Fill in the table below with the test accuracy. Comment on how BoW's performance changes when trained and tested on the 20-newsgroup dataset _without headers and footers_. Does this support our hypothesis from Part (a)?

<font color='red'>**Your Answer Here**</font>

Accuracy Scores
* 200 Training Examples: 49.8.0%
* All Examples: 67.3%

Models performance reduced significantly. This verifies our hypothesis earlier that BoW model uses header for getting better classification results.

## Part (c): Build a Fine-Tuned Model [10 Points]

Now, let's fine tune the GloVe embeddings for our particular dataset. Copy your code from Problem 2, but now change `trainable=True` in `embedding_layer`. Do not change anything else about the model.

In [41]:
embedding_layer = keras.layers.Embedding(
    max_tokens, embedding_dim,embeddings_initializer=keras.initializers.Constant(embedding_matrix), trainable=True, mask_zero=True
)

### YOUR CODE BELOW ###
inputs = keras.Input(shape=(max_length,))
x = embedding_layer(inputs)
x = keras.layers.GlobalAveragePooling1D()(x)
x = keras.layers.Dense(128, activation='relu')(x)
x = keras.layers.Dropout(0.2)(x)
x = keras.layers.Dense(128, activation='relu')(x)
x = keras.layers.Dropout(0.2)(x)

outputs = keras.layers.Dense(y_train.shape[1], activation='softmax')(x)
### YOUR CODE ABOVE ###

glove_model_tuned = keras.Model(inputs, outputs)
glove_model_tuned.summary()

# Compile model using Adam
glove_model_tuned.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy']
)

# Fit model on the training data with 20 epochs and batch size of 32
glove_model_tuned.fit(
    x=X_train_glove[:200], y=y_train[:200],
    epochs=20, batch_size=32,
    verbose=1,
)

print("\n*** Test accuracy with 200 Examples %.4f ***\n" % glove_model_tuned.evaluate(x=X_test_glove, y=y_test)[1])

# Fit model on the training data with 20 epochs and batch size of 32
glove_model_tuned.fit(
    x=X_train_glove, y=y_train,
    epochs=20, batch_size=32,
    verbose=1,
)

print("\n*** Test accuracy with All Examples %.4f ***\n" % glove_model_tuned.evaluate(x=X_test_glove, y=y_test)[1])

Model: "functional_10"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_10      │ (None, 400)       │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_4         │ (None, 400, 300)  │    600,000 │ input_layer_10[0… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ not_equal_1         │ (None, 400)       │          0 │ input_layer_10[0… │
│ (NotEqual)          │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ global_average_poo… │ (None, 300)       │          0 │ embedding_4[0][0… │
│ (GlobalAveragePool… │                   │            │ not_equal_1[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_21 (Dense)    │ (None, 128)       │     38,528 │ global_average_p… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_2 (Dropout) │ (None, 128)       │          0 │ dense_21[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_22 (Dense)    │ (None, 128)       │     16,512 │ dropout_2[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_3 (Dropout) │ (None, 128)       │          0 │ dense_22[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_23 (Dense)    │ (None, 6)         │        774 │ dropout_3[0][0]   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 655,814 (2.50 MB)

 Trainable params: 655,814 (2.50 MB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 5s 266ms/step - accuracy: 0.2050 - loss: 1.7736
Epoch 2/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.2600 - loss: 1.7486
Epoch 3/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.3000 - loss: 1.7150
Epoch 4/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.3500 - loss: 1.6784
Epoch 5/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4350 - loss: 1.6222
Epoch 6/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4350 - loss: 1.5837
Epoch 7/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4250 - loss: 1.5124
Epoch 8/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5800 - loss: 1.4057
Epoch 9/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5950 - loss: 1.3047
Epoch 10/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6750 - loss: 1.2025
Epoch 11/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7500 - loss: 1.0646
Epoch 12/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7700 - loss: 0.9519
Epoch 13/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8150 - loss: 0.7906
Epoch 14/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8450 - loss: 0.7122
Epoch 15/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8750 - loss: 0.5642
Epoch 16/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8800 - loss: 0.4888
Epoch 17/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9250 - loss: 0.3973
Epoch 18/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9300 - loss: 0.3397
Epoch 19/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9450 - loss: 0.2600
Epoch 20/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9650 - loss: 0.2071
68/68 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.6937 - loss: 0.8589

*** Test accuracy with 200 Examples 0.6937 ***

Epoch 1/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - accuracy: 0.7744 - loss: 0.6111
Epoch 2/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8802 - loss: 0.3415
Epoch 3/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9283 - loss: 0.2091
Epoch 4/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9556 - loss: 0.1389
Epoch 5/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9693 - loss: 0.0988
Epoch 6/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9820 - loss: 0.0658
Epoch 7/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9879 - loss: 0.0441
Epoch 8/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9916 - loss: 0.0363
Epoch 9/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9960 - loss: 0.0223
Epoch 10/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9963 - loss: 0.0207
Epoch 11/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9960 - loss: 0.0182
Epoch 12/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9938 - loss: 0.0200
Epoch 13/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9941 - loss: 0.0209
Epoch 14/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9963 - loss: 0.0117
Epoch 15/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9966 - loss: 0.0120
Epoch 16/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9969 - loss: 0.0114
Epoch 17/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9991 - loss: 0.0056
Epoch 18/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9984 - loss: 0.0071
Epoch 19/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9981 - loss: 0.0067
Epoch 20/20
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9981 - loss: 0.0060
68/68 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8112 - loss: 1.0478

*** Test accuracy with All Examples 0.8112 ***

Report the performance of our Glove Model above with fine tuning. Comment on this performance and compare it to that of the GloVe model without fine tuning. Explain when fine-tuning can be helpful and/or hurtful.

**<font color='red'>Answere:</font>**


* 200 Examples: 69.0%
* All Examples: 80.0%

Fine tuning made the performance better for all examples and not that good for 200 examples. This makes sense, when we have only a few examples, fine tuning leads to a lot of overfitting. On the other hand, when we have many examples, fine tuning leads to better embedding that are tailored towasrds a particular classification task that cap and thus better overall performance.

The embedding for the token `henryzootorontoedu` is now no longer all 0's. Nice!

In [42]:
print('The embedding for token %d is' % idx, glove_model_tuned.layers[1].weights[0][idx, :])

The embedding for token 1121 is tf.Tensor(
[-0.08904565 -0.21201457  0.0388522  -0.1125812  -0.18976809 -0.11572155
  0.02549486  0.01980693 -0.03588753 -0.15655196  0.23540042 -0.01740871
  0.13290575  0.12085324 -0.17550048  0.16100806  0.18953094  0.20765379
  0.14312637  0.01448543  0.17707759 -0.13048773  0.18191263  0.20617145
  0.17977582  0.15172979  0.11045417  0.13378835  0.09093418 -0.09876261
  0.20621744 -0.18492137  0.09659029  0.08153679 -0.14938107 -0.09716842
  0.04238201  0.12263861  0.1728274   0.13193008 -0.10281297  0.12627245
 -0.13714506  0.11211809 -0.19778928 -0.14486915 -0.09665868  0.17900187
  0.01889497 -0.17651246 -0.15251604  0.08329385 -0.21031243  0.22220862
 -0.1226134   0.17252265  0.07931257  0.19300574  0.01005186 -0.11010591
 -0.15498286  0.01707778  0.06101321 -0.15910204  0.06341874 -0.0457495
 -0.02321424  0.19782333  0.02475138 -0.0875887   0.20303354  0.16032724
  0.13685837  0.14135416  0.00211947  0.12636949  0.07568571  0.02007418
  0.15953347  0.18753682 -0.15640195 -0.02135083 -0.17890586  0.02131423
  0.05358157 -0.1326225  -0.13840435  0.10868668  0.07961917 -0.14506808
  0.1146771   0.12719955 -0.14801     0.17856841 -0.19826667 -0.14482932
 -0.18668656 -0.01262896  0.03914465 -0.15175757  0.0863867   0.16573885
 -0.19345105  0.1670319   0.18322828 -0.00129243 -0.1966347  -0.05591996
  0.06968451 -0.16513644 -0.18393378 -0.10104627  0.18344313  0.06869253
 -0.15890652  0.05506621 -0.14878325  0.10456493  0.20479861  0.16929442
  0.1625583  -0.06957145  0.08908062  0.18185858 -0.17401029  0.15690674
 -0.15432025  0.06810509  0.15739578 -0.08864866 -0.19024019 -0.21755026
  0.03880154 -0.0335399  -0.06246264 -0.20286717 -0.16468999  0.14510383
 -0.19601245 -0.13592596 -0.21561906 -0.15216354  0.10195529  0.18793447
  0.13868159 -0.20074266  0.00845534  0.18106066  0.15976077 -0.17339262
  0.139612    0.02698432 -0.19637291  0.01152799  0.1949278  -0.13591357
  0.06194577  0.21637127 -0.14752586 -0.01382362  0.02667964 -0.19793656
  0.13878714  0.16874483  0.11301619 -0.1864452  -0.14472444 -0.18516287
  0.1620089   0.01076507 -0.15473561 -0.14436509  0.13353704 -0.19312273
 -0.08360462  0.20531961 -0.07285862 -0.14189698  0.04573803 -0.08420889
  0.09551134 -0.07131168  0.16237736 -0.14640695  0.14387353  0.03097042
 -0.02368136 -0.17126282 -0.00437756 -0.17881756  0.13786767  0.07119262
 -0.02276635  0.17108634  0.10593389  0.12709564  0.13871454  0.07395365
  0.20759667 -0.1637492   0.1896193   0.02522301 -0.18917546  0.12061062
  0.14364693 -0.02096504 -0.06757391  0.044481    0.19755203  0.17912537
  0.13419884 -0.10361531 -0.14450462 -0.15499347 -0.07133481  0.17367038
 -0.0290342   0.03167976 -0.2348676  -0.21710958  0.1443591   0.20329937
 -0.1920177   0.1978965   0.15350707 -0.190382   -0.17268313 -0.1459222
  0.15380314 -0.16031605  0.14255328  0.16822378 -0.18990125 -0.19171588
  0.03625489  0.17958324  0.02132532  0.04057432  0.15857032 -0.01288685
 -0.11556061  0.2110121  -0.05946991 -0.16158192 -0.14523616 -0.12988248
  0.12533037 -0.02464934 -0.14856967  0.12957306 -0.16004325  0.17057782
 -0.02589106 -0.13010056 -0.14725657 -0.10705013 -0.04978589 -0.04711901
 -0.18792625  0.18463053  0.2202894   0.20635296  0.18458726 -0.16523337
 -0.19926417 -0.18872865 -0.15619263  0.18687537  0.15148617  0.07718702
 -0.14721727  0.0945409   0.11472416 -0.03577635 -0.08636692 -0.17467104
  0.03381614 -0.19586195 -0.10557505 -0.205781   -0.13848405  0.2044295
  0.16457833 -0.17286442  0.11006857 -0.07307589 -0.00889888 -0.00522472
 -0.1392361   0.1277917  -0.168732    0.10869197 -0.10411908  0.09093121
  0.13275962  0.07955787 -0.19133696 -0.11039082 -0.14965525 -0.06768816], shape=(300,), dtype=float32)

# Problem 4: BERT Transformer Model [15 Points]

Finally, we use will a famous transformer pre-trained model called [Bert](https://en.wikipedia.org/wiki/BERT_(language_model)). Just like how ResNet was a pre-trained model for computer vision (image processing), BERT is a pre-trained model for natural language processing.

In [6]:
!pip install -q -U tensorflow-text ## install the package for NLP tasks in tensorflow

In [7]:
import tensorflow_hub as hub
import tensorflow_text

bert_preprocess = 'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'

bert_layers = 12
bert_units = 768
bert_heads = 12

bert_encoder = f'https://tfhub.dev/tensorflow/bert_en_uncased_L-{bert_layers}_H-{bert_units}_A-{bert_heads}/4'

/usr/local/lib/python3.13/dist-packages/tensorflow_hub/__init__.py:61: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import parse_version

Let's look to some examples of the text processing required for BERT:

In [8]:
bert_preprocess_model = hub.KerasLayer(bert_preprocess)

text_test = ['This is comedy as it once was and comparing this with the two remakes.']
text_preprocessed = bert_preprocess_model(text_test)
print(f'Word Ids   : {text_preprocessed["input_word_ids"]}')

text_test = ['Although I rated this movie a 2 for showing a complete lack of effort in trying to create a quality horror film it was a 10 on the unintentional funny scale.']
text_preprocessed = bert_preprocess_model(text_test)
print(f'Word Ids   : {text_preprocessed["input_word_ids"]}')

Word Ids   : [[  101  2023  2003  4038  2004  2009  2320  2001  1998 13599  2023  2007
   1996  2048 12661  2015  1012   102     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0]]
Word Ids   : [[  101  2348  1045  6758  2023  3185  1037  1016  2005  4760  1037  3143
   3768  1997  3947  1999  2667  2000  3443  1037  3737  5469  2143  2009
   2001  1037  2184  2006  1996  4895 18447  4765 19301  6057  4094  1012
    102     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0]]

Notice how all examples start with the token `101` and end with `102` (and then followed by `[PAD]` tokens as indicated by 0). Those are special placeholder tokens that can be used for different purposes. For this exercise, we will only concern about the first one, and we will call this token the 'classification token', or `[CLS]`.

The two functions below are used to convert text into tokens (`bert_textvect`) and tokens into embeddings (`bert_features`). You do not need to understand exactly how the functions below work. Note that the following cell may take some time to run (up to 5 minutes).

In [ ]:
max_length = 512

# Load the TensorFlow Hub models directly
preprocessor = hub.load(bert_preprocess)
encoder = hub.load(bert_encoder)
def bert_textvect(x):
    """
    Converts a list of strings into BERT input tokens.
    """
    texts = tf.constant(x.astype(str).tolist(), dtype=tf.string)

    # Tokenize the text
    tokenized_input = preprocessor.tokenize(texts)

    # Pack the tokens into BERT input format
    output = preprocessor.bert_pack_inputs(
        [tokenized_input],
        seq_length=max_length
    )

    return output

def bert_features(x, batch_size=16):
    """
    Converts BERT tokens into 768-dimensional embeddings.
    Uses the [CLS] token representation.
    """
    all_features = []

    n = int(x["input_word_ids"].shape[0])

    for start in range(0, n, batch_size):
        # Select a batch
        batch = {
            key: value[start:start + batch_size]
            for key, value in x.items()
        }

        # Extract BERT features
        output = encoder(batch)

        # Take the [CLS] token embedding
        features = output["sequence_output"][:, 0, :].numpy()
        all_features.append(features)

    return np.concatenate(all_features, axis=0)

X_bert_train = bert_textvect(train_df["text"])
X_bert_test = bert_textvect(test_df["text"])

features_train = bert_features(X_bert_train)
features_test = bert_features(X_bert_test)

print(features_train.shape)
print(features_test.shape)

Next, we'll use the BERT output embedding for the CLS token as input to train a simple neural net. Please build a neural network with 2 dense layers of 128 neurons each using a ReLU activation. Each dense layer should be followed by a Dropout layer with probability of 0.1.

In [ ]:
### YOUR CODE BELOW ###
input = keras.Input(shape=(bert_units, ))

x = keras.layers.Dense(128, activation='relu')(input)
x = keras.layers.Dropout(0.1)(x)
x = keras.layers.Dense(128, activation='relu')(x)
x = keras.layers.Dropout(0.1)(x)

output = keras.layers.Dense(y_train.shape[1], activation='softmax')(x)
### YOUR CODE ABOVE ###

# Model
bert_model = keras.Model(input, output)
bert_model.summary()

bert_model.compile(optimizer="adam",
              loss="categorical_crossentropy",
              metrics=["accuracy"])

bert_model.fit(
    x=features_train[:200], y=y_train[:200],
    epochs=20, batch_size=32,
    verbose=1,
)
print("\n*** Test accuracy with 200 Examples %.4f ***\n" % bert_model.evaluate(x=features_test, y=y_test)[1])

bert_model.fit(
    x=features_train, y=y_train,
    epochs=20, batch_size=32,
    verbose=1,
)
print("\n*** Test accuracy with All Examples %.4f ***\n" % bert_model.evaluate(x=features_test, y=y_test)[1])

Fill in the table below with the accuracies from above. Comment on the performance of the model relative to the BoW and GloVe models.

<font color='red'>**Your Answer Here**</font>

BERT Model Accuracy
* 200 Examples: 0.0%
* All Examples: 0.0%

_Replace this with your answer_

# Conclusion [5 Points]

Please discuss any general take-aways from this homework exercise.

<font color='red'>**Your Answer Here**</font>

_Replace this with your answer_